sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 10
branches:
  only:
    - master
notifications:
  email: false
script:
  - npm run lint && npm run format && npm run build
